<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = json_decode(<<<'JSON'
[
  {"title":"Cablebús Línea 1","title_en":"Cablebus Line 1","address":"Ciudad de México","address_en":"Mexico City","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":"Sistema de transporte público elevado por cable en la zona norte de la Ciudad de México, diseñado para mejorar la conectividad urbana y reducir tiempos de traslado.","description_en":"Elevated cable public transportation system in northern Mexico City, designed to improve urban connectivity and reduce travel times.","latitude":"19.5577669","longitude":"-99.1344122","marker_image":"projects/CablebusL1.jpg"},
  {"title":"Cablebús Línea 3","title_en":"Cablebus Line 3","address":"Ciudad de México","address_en":"Mexico City","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":"Infraestructura de movilidad sustentable que conecta zonas estratégicas de la Ciudad de México mediante transporte por cable.","description_en":"Sustainable mobility infrastructure connecting strategic areas of Mexico City through cable transport.","latitude":"19.3992386","longitude":"-99.2267458","marker_image":"projects/CablebusL3.jpg"},
  {"title":"Ampliación Línea 12 del Metro","title_en":"Metro Line 12 Extension","address":"Ciudad de México","address_en":"Mexico City","category":4,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":"Ampliación de infraestructura ferroviaria urbana para fortalecer la conectividad del sistema Metro en la Ciudad de México.","description_en":"Urban railway infrastructure extension designed to strengthen connectivity within Mexico City Metro system.","latitude":"19.3869070","longitude":"-99.1969780","marker_image":"projects/linea12.jpg"},
  {"title":"Aeropuerto Internacional Ángel Albino Corzo","title_en":"Angel Albino Corzo International Airport","address":"Chiapas","address_en":"Chiapas","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"16.5591700","longitude":"-93.0230900","marker_image":"projects/legacy-1-Centro-de-Congresos-de-Huatulco---copia.jpg"},
  {"title":"Calzada Flotante","title_en":"Floating Causeway","address":"Ciudad de México","address_en":"Mexico City","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.4213850","longitude":"-99.1943750","marker_image":"projects/legacy-25-Calzada-Flotante-CDMX---copia.jpg"},
  {"title":"Carretera Atlacomulco","title_en":"Atlacomulco Highway","address":"Estado de México","address_en":"State of Mexico","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.5764200","longitude":"-99.7575580","marker_image":"projects/legacy-39-Libramiento-Acambay---copia.webp"},
  {"title":"Carretera México-Toluca","title_en":"Mexico-Toluca Highway","address":"Estado de México","address_en":"State of Mexico","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.4765000","longitude":"-99.3134100","marker_image":"projects/legacy-40-Carretera-Mexico-Toluca---copia.webp"},
  {"title":"Circuito Interior","title_en":"Circuito Interior","address":"Ciudad de México","address_en":"Mexico City","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.4153350","longitude":"-99.0986840","marker_image":"projects/legacy-26-circuito-interior-cdmx---copia.webp"},
  {"title":"Deprimido Lilas","title_en":"Lilas Underpass","address":"Ciudad de México","address_en":"Mexico City","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.3871490","longitude":"-99.2476730","marker_image":"projects/legacy-41-Deprimido-Lilas---copia.webp"},
  {"title":"Distribuidor San Jerónimo - Las Flores","title_en":"San Jeronimo - Las Flores Interchange","address":"Ciudad de México","address_en":"Mexico City","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.3310970","longitude":"-99.2105290","marker_image":"projects/legacy-11-Distribuidor-San-Jeronimo-Las-Flores---copia.webp"},
  {"title":"Distribuidor Vial La Concordia","title_en":"La Concordia Road Interchange","address":"Ciudad de México","address_en":"Mexico City","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.3593590","longitude":"-98.9961600","marker_image":"projects/legacy-12-Distribuidor-Vial-La-Concordia---copia.webp"},
  {"title":"Distribuidor Vial de Muyuguarda","title_en":"Muyuguarda Road Interchange","address":"Ciudad de México","address_en":"Mexico City","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.2810090","longitude":"-99.1165210","marker_image":"projects/legacy-13-Distribuidor-Vial-Muyguarda---copia.webp"},
  {"title":"Distribuidor Vial Subterráneo Insurgentes Mixcoac","title_en":"Insurgentes Mixcoac Underground Road Interchange","address":"Ciudad de México","address_en":"Mexico City","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.3784940","longitude":"-99.1924980","marker_image":"projects/legacy-27-vial-subterraneo-insurgentes-mixcoac---copia.webp"},
  {"title":"El Ojite","title_en":"El Ojite","address":"Veracruz","address_en":"Veracruz","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"20.9696560","longitude":"-97.5275380","marker_image":"projects/legacy-17-e-vehicular-el-ojite-tuxpan-veracruz---copia.webp"},
  {"title":"Libramiento Acambay","title_en":"Acambay Bypass","address":"Estado de México","address_en":"State of Mexico","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.9721590","longitude":"-99.8928730","marker_image":"projects/legacy-14-Libramiento-Acambay---copia.webp"},
  {"title":"Libramiento Ciudad Valles-Tamuín","title_en":"Ciudad Valles-Tamuin Bypass","address":"San Luis Potosí","address_en":"San Luis Potosi","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":"Obra de infraestructura vial que incluye el Puente Tampaón II. Implicó el movimiento de 1.4 millones de m³ de material y la ejecución de pilas de cimentación de hasta 44 metros de profundidad sobre el cauce del río. Destaca por el uso pionero de bases cementadas con zeolitas (Road Cem) en una obra de la SCT, superando retos extremos de fraguado bajo altas temperaturas.","description_en":"Road infrastructure project that includes the Tampaon II Bridge. It involved moving 1.4 million cubic meters of material and building foundation piles up to 44 meters deep over the riverbed. It stands out for the pioneering use of cement-treated bases with zeolites (Road Cem) in an SCT project, overcoming extreme setting challenges under high temperatures.","latitude":"21.9850840","longitude":"-99.0038740","marker_image":"projects/legacy-42-Libramiento-Ciudad-Valles-Tamuin---copia.webp"},
  {"title":"Mexibús Línea 1","title_en":"Mexibus Line 1","address":"Estado de México","address_en":"State of Mexico","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.6471750","longitude":"-99.0044820","marker_image":"projects/legacy-28-mexibus-lineas-1-2-cdmx---copia.webp"},
  {"title":"Mexibús Línea 2","title_en":"Mexibus Line 2","address":"Estado de México","address_en":"State of Mexico","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.6119380","longitude":"-99.0587550","marker_image":"projects/legacy-29-mexibus-lineas-1-2-cdmx---copia.webp"},
  {"title":"Nueva Italia-Apatzingán","title_en":"Nueva Italia-Apatzingan","address":"Michoacán","address_en":"Michoacan","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.0656740","longitude":"-102.3528090","marker_image":"projects/legacy-35-acabus-acapulco---copia.webp"},
  {"title":"Parque Lineal Gran Canal","title_en":"Gran Canal Linear Park","address":"Ciudad de México","address_en":"Mexico City","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.4469530","longitude":"-99.1015380","marker_image":"projects/legacy-37-Parque-Lineal-Gran-Canal---copia.webp"},
  {"title":"Puente Atirantado Aeropuerto","title_en":"Airport Cable-Stayed Bridge","address":"Ciudad de México","address_en":"Mexico City","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.4168840","longitude":"-99.0980460","marker_image":"projects/legacy-16-Puente-Aeropuerto---copia.webp"},
  {"title":"Puente de Rodamiento Aeronáutico ASUR Cancún","title_en":"ASUR Cancun Aircraft Taxiway Bridge","address":"Quintana Roo","address_en":"Quintana Roo","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"21.0412680","longitude":"-86.8714200","marker_image":"projects/legacy-23-Puente-Rodamiento-Aeropuerto-Asur-Cancun-Copia.webp"},
  {"title":"Tramo Carretero Jala-Compostela","title_en":"Jala-Compostela Highway Section","address":"Nayarit","address_en":"Nayarit","category":1,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"21.1308000","longitude":"-104.9059320","marker_image":"projects/legacy-43-Mantenimiento-Rehabilitacion-Operacion-Tramo-Carretero-Jala-Compostela---copia.webp"},
  {"title":"Aduana Modelo Reynosa","title_en":"Reynosa Model Customs Facility","address":"Tamaulipas","address_en":"Tamaulipas","category":2,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"26.0433560","longitude":"-98.2101670","marker_image":"projects/legacy-38-Aduana-Modelo-Reynosa---copia.webp"},
  {"title":"Centro de Convenciones de La Paz","title_en":"La Paz Convention Center","address":"Baja California Sur","address_en":"Baja California Sur","category":2,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"24.3177970","longitude":"-110.3296950","marker_image":"projects/legacy-2-centro-de-convenciones-la-paz---copia.webp"},
  {"title":"Centro De Gobierno Guerrero","title_en":"Guerrero Government Center","address":"Guerrero","address_en":"Guerrero","category":2,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"17.5287180","longitude":"-99.4951190","marker_image":"projects/legacy-5-centro-de-gobierno-guerrero---copia.webp"},
  {"title":"Centro Nacional De Las Artes","title_en":"National Center for the Arts","address":"Ciudad de México","address_en":"Mexico City","category":2,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.3565630","longitude":"-99.1411500","marker_image":"projects/legacy-6-centro-nacional-de-las-artes---copia.webp"},
  {"title":"Colegio Green Hills","title_en":"Green Hills School","address":"Ciudad de México","address_en":"Mexico City","category":2,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.3230010","longitude":"-99.2371030","marker_image":"projects/legacy-7-colegio-green-hills-cdmx---copia.webp"},
  {"title":"Colegio Nacional De Economistas","title_en":"National College of Economists","address":"Ciudad de México","address_en":"Mexico City","category":2,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.4345770","longitude":"-99.1603620","marker_image":"projects/legacy-8-colegio-nacional-de-economistas---copia.webp"},
  {"title":"Hospital ISSSTE Morelos","title_en":"ISSSTE Morelos Hospital","address":"Morelos","address_en":"Morelos","category":2,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"18.9225750","longitude":"-99.2060030","marker_image":"projects/legacy-9-hospital-issste-morelos---copia.webp"},
  {"title":"Hospital ISSSTE Veracruz","title_en":"ISSSTE Veracruz Hospital","address":"Veracruz","address_en":"Veracruz","category":2,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.1725140","longitude":"-96.1343650","marker_image":"projects/legacy-10-hospital-issste-veracruz---copia.webp"},
  {"title":"Museo Iztapalapa","title_en":"Iztapalapa Museum","address":"Ciudad de México","address_en":"Mexico City","category":2,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.3465840","longitude":"-99.0657270","marker_image":"projects/legacy-51-museo-Infantil-Iztapalapa---copia.jpg"},
  {"title":"Senado de la República","title_en":"Senate of the Republic","address":"Ciudad de México","address_en":"Mexico City","category":2,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":"Edificación gubernamental monumental construida con 75,000 toneladas de acero estructural y colados ininterrumpidos de 20,000 m³ de concreto en 24 horas. Primera obra en México en utilizar el sistema Top Down para cimentación profunda en el inestable subsuelo del Lago de Tenochtitlán, alcanzando pilas de hasta 45 metros de profundidad.","description_en":"Monumental government building constructed with 75,000 tons of structural steel and uninterrupted pours of 20,000 cubic meters of concrete over 24 hours. It was the first project in Mexico to use the Top Down system for deep foundations in the unstable subsoil of Lake Texcoco, reaching piles up to 45 meters deep.","latitude":"19.4367350","longitude":"-99.1924760","marker_image":"projects/legacy-19-senado-de-la-republica-panoramica---copia.jpg"},
  {"title":"Tribunal Superior de Justicia","title_en":"Superior Court of Justice","address":"Ciudad de México","address_en":"Mexico City","category":2,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.4219370","longitude":"-99.1501880","marker_image":"projects/legacy-22-tribunal-superior-de-justicia-cdmx---copia.webp"},
  {"title":"Fase 2 y 3 Puerto de Manzanillo","title_en":"Phases 2 and 3 of the Port of Manzanillo","address":"Colima","address_en":"Colima","category":3,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.0560000","longitude":"-104.3181000","marker_image":"projects/legacy-101-puerto-manzanillo-1---copia.webp"},
  {"title":"Rompeolas Salina Cruz","title_en":"Salina Cruz Breakwater","address":"Oaxaca","address_en":"Oaxaca","category":3,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":"Obra marítima colosal, catalogada como el rompeolas más grande de Latinoamérica. Su construcción implicó el vertimiento récord de 15,000 toneladas diarias, sumando casi 6 millones de toneladas de roca y 11,000 prefabricados de concreto (Corelocs). Destaca el uso pionero de drones robóticos marinos y posicionamiento GPS de precisión milimétrica.","description_en":"Colossal maritime work, recognized as the largest breakwater in Latin America. Its construction involved a record placement of 15,000 tons per day, totaling nearly 6 million tons of rock and 11,000 precast concrete Coreloc units. It stands out for the pioneering use of marine robotic drones and millimeter-precision GPS positioning.","latitude":"16.1414000","longitude":"-95.2040000","marker_image":"projects/legacy-102-Rompe-Olas-Salina-Cruz-Oaxaca-3---copia.jpg"},
  {"title":"Muelle Lerma","title_en":"Lerma Dock","address":"Campeche","address_en":"Campeche","category":3,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.8050000","longitude":"-90.6041000","marker_image":"projects/legacy-103-muelle-lerma-campeche---copia.webp"},
  {"title":"Nueva Terminal Portuaria de Veracruz","title_en":"New Port Terminal of Veracruz","address":"Veracruz","address_en":"Veracruz","category":3,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":"Desarrollo y modernización de infraestructura portuaria estratégica. El proyecto incluyó la ampliación de capacidades operativas y logísticas marítimas para optimizar el flujo de comercio internacional, empleando ingeniería de vanguardia para garantizar la estabilidad de las nuevas instalaciones frente a las exigentes dinámicas costeras.","description_en":"Development and modernization of strategic port infrastructure. The project included expanding maritime operational and logistics capacity to optimize international trade flow, using advanced engineering to ensure the stability of new facilities against demanding coastal dynamics.","latitude":"19.2359000","longitude":"-96.1702000","marker_image":"projects/legacy-104-a-terminal-portuaria-puerto-veracruz---copia.webp"},
  {"title":"Terminal de Contenedores Muelle Lázaro Cárdenas","title_en":"Lazaro Cardenas Dock Container Terminal","address":"Michoacán","address_en":"Michoacan","category":3,"status":true,"home_order":2,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"17.9536000","longitude":"-102.1731000","marker_image":"projects/legacy-105-contenedores-muelle-lazaro-cardenas.webp"},
  {"title":"Puente Marítimo Ignacio Chávez","title_en":"Ignacio Chavez Maritime Bridge","address":"Michoacán","address_en":"Michoacan","category":3,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"17.9921000","longitude":"-102.1760000","marker_image":"projects/legacy-106-Puente-Maritimo-Ignacio-Chavez---copia.webp"},
  {"title":"Morro Rompeolas Isla del Carmen","title_en":"Isla del Carmen Breakwater Head","address":"Campeche","address_en":"Campeche","category":3,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"18.6473000","longitude":"-91.8538000","marker_image":"projects/legacy-107-morro-rompeolas-isla-del-carmen---copia.webp"},
  {"title":"Patio Martín Carrera","title_en":"Martin Carrera Yard","address":"Ciudad de México","address_en":"Mexico City","category":4,"status":true,"home_order":null,"home_year":null,"home_time":null,"home_time_en":null,"description":null,"description_en":null,"latitude":"19.4838600","longitude":"-99.1054110","marker_image":"projects/legacy-31-patio-martin-carrera-cdm---copia.webp"},
  {"title":"Planta de Durmientes del Tren Maya","title_en":"Maya Train Sleeper Plant","address":"Yucatán","address_en":"Yucatan","category":4,"status":true,"home_order":1,"home_year":null,"home_time":null,"home_time_en":null,"description":"Planta industrial automatizada de alta complejidad para prefabricados ferroviarios. Alcanzó un récord de producción de 1,654 durmientes diarios, fabricando más de 657,000 unidades con cero rechazos. Implementó robótica avanzada y una fórmula exclusiva de concreto que logra la resistencia para pretensado en solo 10 horas.","description_en":"Highly complex automated industrial plant for railway precast elements. It reached a production record of 1,654 sleepers per day, manufacturing more than 657,000 units with zero rejections. It implemented advanced robotics and an exclusive concrete formula that achieves prestressing strength in just 10 hours.","latitude":"20.8697780","longitude":"-89.5768040","marker_image":"projects/legacy-32-Fabrica-de-Durmientes-Merida-1---copia.jpg"},
  {"title":"Tren Maya Tramo 3 'Calkiní-Izamal'","title_en":"Maya Train Section 3 Calkini-Izamal","address":"Yucatán","address_en":"Yucatan","category":4,"status":true,"home_order":3,"home_year":"2024","home_time":null,"home_time_en":null,"description":"Construcción de plataforma ferroviaria y tendido de vía férrea a lo largo de un trazado estratégico de alta complejidad logística. El proyecto superó desafíos topográficos y climáticos mediante una planificación impecable, garantizando la integración de sistemas ferroviarios de carga y pasajeros de última generación.","description_en":"Construction of the railway platform and track installation along a strategically important route with high logistics complexity. The project overcame topographic and climate challenges through flawless planning, ensuring the integration of next-generation freight and passenger rail systems.","latitude":"20.3708660","longitude":"-90.0498280","marker_image":"projects/legacy-34-Tren-Maya-Tramos-3-y-5-a---copia.jpg"}
]
JSON, true);

        foreach ($projects as $project) {
            Project::query()->updateOrCreate([
                'title' => $project['title'],
                'address' => $project['address'],
            ], $project);
        }
    }
}
