@extends('layouts.app')

@section('title', 'AVISO DE PRIVACIDAD | INDI')

@section('content')
<section class="privacy-page">
    <div class="privacy-hero">
        <div class="privacy-kicker">INDI / INFORMACIÓN LEGAL</div>
        <h1>AVISO DE<br><span>PRIVACIDAD</span></h1>
        <p>La protección de tus datos personales es parte de nuestro compromiso.</p>
    </div>
    <article class="privacy-document">
        <div class="privacy-document-head">
            <span>GRUPO INDI, S.A. DE C.V.</span>
            <span>ACTUALIZACIÓN VIGENTE</span>
        </div>
        <div class="privacy-copy">
<p>GRUPO INDI, S.A. DE C.V. (en lo sucesivo GRUPO INDI) con domicilio ubicado en: Boulevard de los Virreyes 135, Colonia Lomas de Chapultepec IV Secc., C.P. 11000, Alcald&#237;a Miguel Hidalgo, Ciudad de M&#233;xico, hace de su conocimiento que en cumplimiento a lo previsto en la Ley Federal de Protecci&#243;n de Datos Personales en Posesi&#243;n de los Particulares (en lo sucesivo la Ley) le informa que es responsable del tratamiento de los datos personales de los visitantes de nuestro sitio web, mismos que son tratados de forma confidencial, para garantizar la privacidad y el derecho a la autodeterminaci&#243;n informativa de los titulares que de manera libre y voluntaria proporcionen datos personales. La obtenci&#243;n, tratamiento, transferencia y ejercicio de los derechos derivados de dichos datos personales, se hace mediante un uso adecuado, leg&#237;timo y l&#237;cito, salvaguardando y atendiendo a los principios de licitud, consentimiento, informaci&#243;n, calidad, finalidad, lealtad, proporcionalidad y responsabilidad previstos y tutelados por el art&#237;culo 6&#186; de la Ley, su Reglamento y dem&#225;s leyes aplicables.</p>
<p>El tratamiento de los datos personales del Titular ser&#225; efectuado de conformidad con los t&#233;rminos establecidos en el presente aviso de privacidad, por lo que, desde este momento se entiende que el Titular otorga su consentimiento para dicho tratamiento.</p>
<p>En GRUPO INDI protegeremos la privacidad de sus datos personales. En raz&#243;n de lo anterior, a continuaci&#243;n se&#241;alamos los datos personales que podremos recabar de usted al momento de visitar nuestro sitio web:</p>
<p>(i) Correo electr&#243;nico.</p>
<p>(ii)Nombre Completo.</p>
<p>(iii)Lugar de donde nos contacta.</p>
<p>Le informamos que GRUPO INDI no recabar&#225; informaci&#243;n considerada como sensible de los visitantes de nuestro sitio web, conforme a lo establecido en la Ley y su Reglamento. Con respecto de los datos personales antes mencionados, se garantiza un tratamiento, directamente a trav&#233;s de GRUPO INDI para las finalidades que dieron origen y son necesarias para la existencia, mantenimiento y cumplimiento de la relaci&#243;n establecida con los visitantes de nuestro sitio web, mismas que se se&#241;alan a continuaci&#243;n:</p>
<p>I.-FINALIDADES DEL TRATAMIENTO DE LOS DATOS PERSONALES</p>
<p>GRUPO INDI recabar&#225; sus Datos Personales, para las finalidades que se refieren a continuaci&#243;n:</p>
<p>1.- Realizar denuncias.</p>
<p>2.- Quejas y sugerencias sobre nuestros servicios.</p>
<p>En caso de que usted desee proporcionarnos informaci&#243;n adicional que no le hayamos requerido directamente, GRUPO INDI</p>
<p>II.- SEGURIDAD</p>
<p>GRUPO INDI cuenta con las medidas de seguridad administrativas, t&#233;cnicas y f&#237;sicas que nos permiten proteger los datos personales que nos son proporcionados contra da&#241;o, p&#233;rdida, alteraci&#243;n, destrucci&#243;n o el uso, acceso o tratamiento no autorizado.</p>
<p>III.- TRANSFERENCIA</p>
<p>Le informamos que los datos personales que sean recabados por GRUPO INDI no ser&#225;n transferidos a terceros, salvo cuando sea necesario en los casos se&#241;alados en el presente Aviso y de conformidad con lo dispuesto en la Ley y su Reglamento. En raz&#243;n de lo anterior, GRUPO INDI le informa que en t&#233;rminos de lo dispuesto por el art&#237;culo 37 de la Ley, no se requerir&#225; de su consentimiento para transferir sus datos personales a terceros, en los siguientes casos:</p>
<p>1.- Cuando la transferencia est&#233; prevista en una Ley o Tratado en los que M&#233;xico sea parte.</p>
<p>2.- Cuando la transferencia sea necesaria para la prevenci&#243;n o el diagn&#243;stico m&#233;dico, la prestaci&#243;n de asistencia sanitaria, tratamiento m&#233;dico o la gesti&#243;n de servicios sanitarios.</p>
<p>3.- Cuando la transferencia sea efectuada a sociedades controladoras, subsidiarias o afiliadas bajo el control com&#250;n del responsable, o a una sociedad matriz o a cualquier sociedad del mismo grupo de GRUPO INDI que opere bajo los mismos procesos y pol&#237;ticas internas.</p>
<p>4.- Cuando la transferencia sea necesaria por virtud de un contrato celebrado o por celebrar en inter&#233;s del titular de datos, por GRUPO INDI y un tercero.</p>
<p>5.- Cuando la transferencia sea necesaria o legalmente exigida para la salvaguarda de un inter&#233;s p&#250;blico o para la procuraci&#243;n o administraci&#243;n de justicia.</p>
<p>6.- Cuando la transferencia sea precisa para el reconocimiento, ejercicio o defensa de un derecho en un proceso judicial.</p>
<p>7.- Cuando la transferencia sea precisa para el mantenimiento o cumplimiento de una relaci&#243;n jur&#237;dica entre GRUPO INDI y el titular de datos.</p>
<p>IV.- MEDIOS PARA EJERCER LOS DERECHOS DE ACCESO, RECTIFICACI&#211;N, CANCELACI&#211;N U OPOSICI&#211;N (DERECHOS ARCO)</p>
<p>GRUPO INDI hace de su conocimiento que el titular de los datos personales o a trav&#233;s de su representante legal o apoderado puede revocar el consentimiento que nos haya otorgado para el tratamiento de sus datos personales en cualquier momento; sin embargo, es importante que tenga en cuenta que no en todos los casos podremos atender su solicitud, ya que es posible que por alguna obligaci&#243;n legal requiramos seguir tratando sus datos personales. Si usted desea limitar el uso del tratamiento de sus datos personales, puede enviarnos un correo electr&#243;nico a la direcci&#243;n: contacto@grupondi.com, donde con gusto le informaremos sobre la procedencia de su petici&#243;n, as&#237; como los procedimientos que tenemos instrumentados para ello.</p>
<p>Para revocar su consentimiento, deber&#225; indicar por escrito o a la direcci&#243;n de correo electr&#243;nico: contacto@grupondi.com de manera precisa el consentimiento que desea revocar.</p>
<p>Cualquier titular, o en su caso su representante legal, podr&#225; revocar el consentimiento que haya otorgado para el tratamiento de sus datos, as&#237; como podr&#225; ejercer los derechos de acceso, rectificaci&#243;n, cancelaci&#243;n y oposici&#243;n previstos en la ley, siendo requisito indispensable agregar a dicha solicitud (escrita o electr&#243;nica) el documento que acredite su identidad (identificaci&#243;n oficial) o en su caso, acreditar la personalidad de quien legalmente le represente. En este sentido los titulares tienen derecho a acceder a sus datos personales que obren en poder de GRUPO INDI (Acceso); a rectificarlos cuando sean inexactos o incompletos (Rectificaci&#243;n); tendr&#225; en todo momento el derecho a cancelar sus datos personales (Cancelaci&#243;n). La cancelaci&#243;n de datos personales dar&#225; lugar a un periodo de bloqueo tras el cual se proceder&#225; a la supresi&#243;n del dato; o bien, oponerse al uso de sus datos personales para fines espec&#237;ficos (Oposici&#243;n), en los casos en que la Ley, as&#237; lo permita; el ejercicio de cualquiera de los derechos antes citados de ellos no es requisito previo ni impide el ejercicio de otro derecho.</p>
<p>En el caso de solicitudes de rectificaci&#243;n de datos personales, el titular deber&#225; indicar, adem&#225;s de la documentaci&#243;n con la que acredite su personalidad, las modificaciones a realizarse y aportar la documentaci&#243;n que sustente su petici&#243;n.</p>
<p>GRUPO INDI atender&#225; su petici&#243;n en los tiempos establecidos en las leyes aplicables y le informar&#225; por escrito y/o a trav&#233;s del correo electr&#243;nico que proporcione para tales efectos, las consecuencias que deban producirse con motivo del ejercicio de sus derechos. La entrega de los datos personales ser&#225; gratuita, debiendo cubrir el titular &#250;nicamente los gastos justificados de env&#237;o o con el costo de reproducci&#243;n en copias u otros formatos.</p>
<p>Para conocer puntualmente el procedimiento establecido por GRUPO INDI para la revocaci&#243;n del consentimiento respecto del tratamiento de sus datos personales y/o respecto del ejercicio de los derechos ARCO, usted podr&#225; acudir personalmente a nuestras oficinas, directamente en nuestro: “Departamento de Datos Personales”, as&#237; como contactar al responsable a trav&#233;s del correo electr&#243;nico: contacto@grupondi.com, donde le informaremos sobre los detalles del procedimiento y requisitos para el ejercicio de sus derechos.</p>
<p>Con fundamento en el art&#237;culo 45 de la Ley, si considera que no ha recibido una respuesta de GRUPO INDI o bien, la respuesta que se le dio no es satisfactoria, usted tiene derecho de acudir al Instituto Nacional de Transparencia, Acceso a la Informaci&#243;n y Protecci&#243;n de Datos Personales (INAI) a presentar una “Solicitud de Protecci&#243;n de Datos Personales” dentro de los 15 (quince d&#237;as) siguientes a la fecha en la que se comunique la respuesta al Titular por parte de GRUPO INDI o a la fecha en que venza el plazo para que GRUPO INDI de respuesta a su solicitud de conformidad con la Ley y su Reglamento, as&#237; como del procedimiento que hemos instaurado para ello.</p>
<p>GRUPO INDI le informa que, para recabar los datos personales que se detallan en el presente documento, no utilizar&#225; mecanismos en medios remotos o locales de comunicaci&#243;n electr&#243;nica, &#243;ptica u otra tecnolog&#237;a, que permitan recabar sus datos personales de manera autom&#225;tica y simult&#225;nea al tiempo que usted hace contacto con los mismos.</p>
<p>MODIFICACIONES AL AVISO DE PRIVACIDAD</p>
<p>Cualquier cambio o modificaci&#243;n al presente Aviso de Privacidad, GRUPO INDI lo comunicar&#225; a trav&#233;s de este mismo medio.</p>
<p>Si desea conocer m&#225;s detalles sobre la Pol&#237;tica de Privacidad de GRUPO INDI usted puede contactar al oficial de Datos Personales a la direcci&#243;n de correo electr&#243;nico: contacto@grupondi.com; comunicarse al n&#250;mero de tel&#233;fono (55) 5540 - 6750 o acudir directamente a nuestras oficinas ubicadas en el domicilio se&#241;alado en el presente documento.</p>
        </div>
        <a class="privacy-back" href="{{ url('/') }}">← VOLVER AL SITIO</a>
    </article>
</section>
@endsection

@push('styles')
<style>
.privacy-page{background:#f4f7fb;color:#101820;font-family:'usual',sans-serif;padding-bottom:8rem}.privacy-hero{min-height:46vh;padding:clamp(8rem,14vw,13rem) clamp(1.5rem,8vw,10rem) 5rem;background:linear-gradient(120deg,#071426 0%,#0a2b58 58%,#0066f9 100%);color:#fff;position:relative;overflow:hidden}.privacy-hero:after{content:'§';position:absolute;right:9%;bottom:-5rem;color:rgba(255,255,255,.08);font:700 28rem/1 Georgia,serif}.privacy-kicker{color:#8db9ff;font-size:.78rem;letter-spacing:.28em;font-weight:700;margin-bottom:2rem}.privacy-hero h1{margin:0;position:relative;z-index:1;font-size:clamp(3rem,8vw,7rem);line-height:.88;letter-spacing:-.04em}.privacy-hero h1 span{color:#8db9ff}.privacy-hero p{position:relative;z-index:1;max-width:36rem;margin:2.5rem 0 0;color:rgba(255,255,255,.76);font-size:clamp(1rem,1.7vw,1.35rem);line-height:1.6}.privacy-document{width:min(90%,960px);margin:-4rem auto 0;position:relative;z-index:2;background:#fff;padding:clamp(1.5rem,5vw,5rem);box-shadow:0 24px 70px rgba(7,20,38,.14);border-top:5px solid #0066f9}.privacy-document-head{display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap;padding-bottom:1.5rem;border-bottom:1px solid #dfe7f0;color:#0066f9;font-size:.72rem;letter-spacing:.15em;font-weight:700}.privacy-copy{color:#465465;font-family:Arial,sans-serif;font-size:1rem;line-height:1.85}.privacy-copy p{margin:1.35rem 0}.privacy-copy p:first-child{font-weight:600;color:#1c2938}.privacy-back{display:inline-flex;margin-top:2.5rem;padding:.9rem 1.25rem;color:#fff;background:#0066f9;text-decoration:none;font-weight:700;font-size:.76rem;letter-spacing:.12em;transition:transform .2s ease,background .2s ease}.privacy-back:hover{background:#0051c7;transform:translateX(4px)}@media(max-width:720px){.privacy-hero{min-height:40vh;padding-top:8rem}.privacy-document{width:calc(100% - 2rem);margin-top:-2rem}.privacy-copy{font-size:.94rem}.privacy-hero:after{font-size:16rem}}
</style>
@endpush